name: deskbuddy
description: "DeskBuddy - App Flutter com OTA via BLE"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.34.5
  get: ^4.6.6
  flutter_rounded_progress_bar: ^0.3.2
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.0.18
  flutter_native_splash: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "0xFFFFF7ED"
  image: assets/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/firmware/    # pasta do firmware OTA .bin
